### ISSUE TITLE
README.md and current status discrepency

### ISSUE THREAD

**Issue by najaco** [fatcat2/fatcat2#1]
In the [README.md](https://github.com/fatcat2/fatcat2/blob/main/README.md), you mention that you are "interested in adopting a dog after graduation". However, I believe that you graduated over a year and a half ago. Is there another graduation that you have planned or have you not updated this since _Dec 11, 2021_?

**Comment by najaco** [comment]
Also is there an update on your goal(s)?:
```
- 🥅  My programming goal for the end of 2020 is to create a Rust microservice bot.
```

**Comment by stephend017** [comment]
I believe he now owns a cat which is in fact not a dog

**Comment by najaco** [comment]
> I believe he now owns a cat which is in fact not a dog

Interesting... this was not in the release notes.

**Comment by fatcat2** [comment]
My humble apologies to all I have concerned. I have lagged in maintaining this repository. I will proceed to ignore all complaints and go play The Sims 4.

**Comment by noah-curran** [comment]
smh dev making us do a PR to finish his half-done work

**Comment by fatcat2** [comment]
If you don't like it, fork it. Closing this issue as it is no longer relevant.
